root - ERROR - list index out of range has happened
Traceback (most recent call last):
  File "c:\Users\csehg\pytry\table_listed03.py", line 85, in <module>
    tmp = f'{kijelolt[0][1]}{kijelolt[0][0]}'
IndexError: list index out of range
